version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - database
    ports:
      - "5432:5432"
    volumes:
      - .:/app
    env_file: .env
    environment:
      RAILS_ENV: development
  database:
    image: postgres:12.1
